"""add summary fields to chat_conversations

Revision ID: bd7663ab2a04
Revises: 3789c641fc64
Create Date: 2026-08-08 08:15:54.918283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7663ab2a04'
down_revision: Union[str, Sequence[str], None] = '3789c641fc64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('chat_conversations', sa.Column('summary_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_conversations', 'summary_updated_at')
    op.drop_column('chat_conversations', 'summary')
    # ### end Alembic commands ###
