"""add embedding column to courses

Revision ID: c74a07a6be69
Revises: 360ad2ff20ae
Create Date: 2026-08-08 06:07:54.853016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'c74a07a6be69'
down_revision: Union[str, Sequence[str], None] = '360ad2ff20ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Must run before add_column below — CREATE EXTENSION registers the
    # `vector` type with Postgres; without it, VECTOR(384) in the next
    # statement has no type to resolve against.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('embedding', Vector(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'embedding')
    # ### end Alembic commands ###
